---
version: '3'
services:
  consuela-db:
    build: ./couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb/etc:/opt/couchdb/etc/local.d
    ports:
      - "5984:5984"
  web:
    build: ./app
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
      - COUCHDB_SERVER=consuela-db:5984
    ports:
      - "3001:3001"
    restart: always
